/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ThrowerrorIndexImport } from './routes/throwerror/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThrowerrorIndexRoute = ThrowerrorIndexImport.update({
  id: '/throwerror/',
  path: '/throwerror/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/throwerror/': {
      id: '/throwerror/'
      path: '/throwerror'
      fullPath: '/throwerror'
      preLoaderRoute: typeof ThrowerrorIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/throwerror': typeof ThrowerrorIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/throwerror': typeof ThrowerrorIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/throwerror/': typeof ThrowerrorIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/throwerror'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/throwerror'
  id: '__root__' | '/' | '/throwerror/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThrowerrorIndexRoute: typeof ThrowerrorIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThrowerrorIndexRoute: ThrowerrorIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/throwerror/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/throwerror/": {
      "filePath": "throwerror/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
